import glob

filenames = glob.glob('data/pokemon/base_stats/*.asm')
mondata = {
## NOTE: Uses Bulbapedia format not the actual format used in the implementation, reordered later
### HP, ATK, DEF, SP.ATK, SP.DEF, SPEED
'data/pokemon/base_stats/abra.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/aerodactyl.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/aipom.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/alakazam.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/ampharos.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/arbok.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/arcanine.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/ariados.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/articuno.asm': ['0', '0', '0', '0', '3', '0'],
'data/pokemon/base_stats/azumarill.asm': ['3', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/bayleef.asm': ['0', '0', '1', '0', '1', '0'],
'data/pokemon/base_stats/beedrill.asm': ['0', '2', '0', '0', '1', '0'],
'data/pokemon/base_stats/bellossom.asm': ['0', '0', '0', '0', '3', '0'],
'data/pokemon/base_stats/bellsprout.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/blastoise.asm': ['0', '0', '0', '0', '3', '0'],
'data/pokemon/base_stats/blissey.asm': ['3', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/bulbasaur.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/butterfree.asm': ['0', '0', '0', '2', '1', '0'],
'data/pokemon/base_stats/caterpie.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/celebi.asm': ['3', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/chansey.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/charizard.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/charmander.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/charmeleon.asm': ['0', '0', '0', '1', '0', '1'],
'data/pokemon/base_stats/chikorita.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/chinchou.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/clefable.asm': ['3', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/clefairy.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/cleffa.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/cloyster.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/corsola.asm': ['0', '0', '1', '0', '1', '0'],
'data/pokemon/base_stats/crobat.asm': ['0', '0', '0', '0', '0', '3'],
'data/pokemon/base_stats/croconaw.asm': ['0', '1', '1', '0', '0', '0'],
'data/pokemon/base_stats/cubone.asm': ['0', '0', '1', '0', '0', '0'],
 'data/pokemon/base_stats/cyndaquil.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/delibird.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/dewgong.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/diglett.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/ditto.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/dodrio.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/doduo.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/donphan.asm': ['0', '1', '1', '0', '0', '0'],
'data/pokemon/base_stats/dragonair.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/dragonite.asm': ['0', '3', '0', '0', '0', '0'],
'data/pokemon/base_stats/dratini.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/drowzee.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/dugtrio.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/dunsparce.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/eevee.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/ekans.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/electabuzz.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/electrode.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/elekid.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/entei.asm': ['1', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/espeon.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/exeggcute.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/exeggutor.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/farfetch_d.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/fearow.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/feraligatr.asm': ['0', '2', '1', '0', '0', '0'],
'data/pokemon/base_stats/flaaffy.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/flareon.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/forretress.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/furret.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/gastly.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/gengar.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/geodude.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/girafarig.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/gligar.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/gloom.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/golbat.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/goldeen.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/golduck.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/golem.asm': ['0', '0', '3', '0', '0', '0'],
'data/pokemon/base_stats/granbull.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/graveler.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/grimer.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/growlithe.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/gyarados.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/haunter.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/heracross.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/hitmonchan.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/hitmonlee.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/hitmontop.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/ho_oh.asm': ['0', '0', '0', '0', '3', '0'],
'data/pokemon/base_stats/hoothoot.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/hoppip.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/horsea.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/houndoom.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/houndour.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/hypno.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/igglybuff.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/ivysaur.asm': ['0', '0', '0', '1', '1', '0'],
'data/pokemon/base_stats/jigglypuff.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/jolteon.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/jumpluff.asm': ['0', '0', '0', '0', '0', '3'],
'data/pokemon/base_stats/jynx.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/kabuto.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/kabutops.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/kadabra.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/kakuna.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/kangaskhan.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/kingdra.asm': ['0', '1', '0', '1', '1', '0'],
'data/pokemon/base_stats/kingler.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/koffing.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/krabby.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/lanturn.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/lapras.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/larvitar.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/ledian.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/ledyba.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/lickitung.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/lugia.asm': ['0', '0', '0', '0', '3', '0'],
'data/pokemon/base_stats/machamp.asm': ['0', '3', '0', '0', '0', '0'],
'data/pokemon/base_stats/machoke.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/machop.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/magby.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/magcargo.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/magikarp.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/magmar.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/magnemite.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/magneton.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/mankey.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/mantine.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/mareep.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/marill.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/marowak.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/meganium.asm': ['0', '0', '1', '0', '2', '0'],
'data/pokemon/base_stats/meowth.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/metapod.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/mew.asm': ['3', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/mewtwo.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/miltank.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/misdreavus.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/moltres.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/mr__mime.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/muk.asm': ['1', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/murkrow.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/natu.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/nidoking.asm': ['0', '3', '0', '0', '0', '0'],
'data/pokemon/base_stats/nidoqueen.asm': ['3', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/nidoran_f.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/nidoran_m.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/nidorina.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/nidorino.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/ninetales.asm': ['0', '0', '0', '0', '1', '1'],
'data/pokemon/base_stats/noctowl.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/octillery.asm': ['0', '1', '0', '1', '0', '0'],
'data/pokemon/base_stats/oddish.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/omanyte.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/omastar.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/onix.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/paras.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/parasect.asm': ['0', '2', '1', '0', '0', '0'],
'data/pokemon/base_stats/persian.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/phanpy.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/pichu.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/pidgeot.asm': ['0', '0', '0', '0', '0', '3'],
'data/pokemon/base_stats/pidgeotto.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/pidgey.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/pikachu.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/piloswine.asm': ['1', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/pineco.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/pinsir.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/politoed.asm': ['0', '0', '0', '0', '3', '0'],
'data/pokemon/base_stats/poliwag.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/poliwhirl.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/poliwrath.asm': ['0', '0', '3', '0', '0', '0'],
'data/pokemon/base_stats/ponyta.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/porygon.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/porygon2.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/primeape.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/psyduck.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/pupitar.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/quagsire.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/quilava.asm': ['0', '0', '0', '1', '0', '1'],
'data/pokemon/base_stats/qwilfish.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/raichu.asm': ['0', '0', '0', '0', '0', '3'],
'data/pokemon/base_stats/raikou.asm': ['0', '0', '0', '1', '0', '2'],
'data/pokemon/base_stats/rapidash.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/raticate.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/rattata.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/remoraid.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/rhydon.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/rhyhorn.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/sandshrew.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/sandslash.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/scizor.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/scyther.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/seadra.asm': ['0', '0', '1', '1', '0', '0'],
'data/pokemon/base_stats/seaking.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/seel.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/sentret.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/shellder.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/shuckle.asm': ['0', '0', '1', '0', '1', '0'],
'data/pokemon/base_stats/skarmory.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/skiploom.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/slowbro.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/slowking.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/slowpoke.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/slugma.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/smeargle.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/smoochum.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/sneasel.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/snorlax.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/snubbull.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/spearow.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/spinarak.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/squirtle.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/stantler.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/starmie.asm': ['0', '0', '0', '0', '0', '2'],
'data/pokemon/base_stats/staryu.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/steelix.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/sudowoodo.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/suicune.asm': ['0', '0', '1', '0', '2', '0'],
'data/pokemon/base_stats/sunflora.asm': ['0', '0', '0', '2', '0', '0'],
'data/pokemon/base_stats/sunkern.asm': ['0', '0', '0', '1', '0', '0'],
'data/pokemon/base_stats/swinub.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/tangela.asm': ['0', '0', '1', '0', '0', '0'],
'data/pokemon/base_stats/tauros.asm': ['0', '1', '0', '0', '0', '1'],
'data/pokemon/base_stats/teddiursa.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/tentacool.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/tentacruel.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/togepi.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/togetic.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/totodile.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/typhlosion.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/tyranitar.asm': ['0', '3', '0', '0', '0', '0'],
'data/pokemon/base_stats/tyrogue.asm': ['0', '1', '0', '0', '0', '0'],
'data/pokemon/base_stats/umbreon.asm': ['0', '0', '0', '0', '2', '0'],
'data/pokemon/base_stats/unown.asm': ['0', '1', '0', '1', '0', '0'],
'data/pokemon/base_stats/ursaring.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/vaporeon.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/venomoth.asm': ['0', '0', '0', '1', '0', '1'],
'data/pokemon/base_stats/venonat.asm': ['0', '0', '0', '0', '1', '0'],
'data/pokemon/base_stats/venusaur.asm': ['0', '0', '0', '2', '1', '0'],
'data/pokemon/base_stats/victreebel.asm': ['0', '3', '0', '0', '0', '0'],
'data/pokemon/base_stats/vileplume.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/voltorb.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/vulpix.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/wartortle.asm': ['0', '0', '1', '0', '1', '0'],
'data/pokemon/base_stats/weedle.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/weepinbell.asm': ['0', '2', '0', '0', '0', '0'],
'data/pokemon/base_stats/weezing.asm': ['0', '0', '2', '0', '0', '0'],
'data/pokemon/base_stats/wigglytuff.asm': ['3', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/wobbuffet.asm': ['2', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/wooper.asm': ['1', '0', '0', '0', '0', '0'],
'data/pokemon/base_stats/xatu.asm': ['0', '0', '0', '1', '0', '1'],
'data/pokemon/base_stats/yanma.asm': ['0', '0', '0', '0', '0', '1'],
'data/pokemon/base_stats/zapdos.asm': ['0', '0', '0', '3', '0', '0'],
'data/pokemon/base_stats/zubat.asm': ['0', '0', '0', '0', '0', '1']
}
count = 1
for filename in filenames:

	with open(filename, 'r', encoding='utf8') as file:
		lines = file.readlines()

	with open(filename, 'w', encoding='utf8') as file:
		for line in lines:
			if line in ['\tdb 100 ; unknown 1\n', '\tdb 5 ; unknown 2\n']:
				continue
			if line == '\t;   hp  atk  def  spd  sat  sdf\n':
				if filename in mondata.keys():
					print(str(count) +': Update', filename)
					hpEV = mondata[filename][0]
					atkEV = mondata[filename][1]
					defEV = mondata[filename][2]
					spdEV = mondata[filename][5]
					satEV = mondata[filename][3]
					sdfEV = mondata[filename][4]
					#
					file.write('\tevs  %s,   %s,   %s,   %s,   %s,   %s\n' % (hpEV, atkEV, defEV, spdEV, satEV, sdfEV ))
					count += 1
				else:
					file.write('\tevs  0,   0,   0,   0,   0,   0\n')

			file.write(line)